"""
Django settings for hakaton project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Родительский каталог репозитория: там же лежат chat.py, gigachat_advisor.py, afisha.db
REPO_ROOT = BASE_DIR.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

try:
    from dotenv import load_dotenv

    load_dotenv(REPO_ROOT / ".env")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-30!__%on3fzapsk=t0ntkfj)%pmo@)_-corg9=9b@y$@=_ohea'

# Регистрация по ссылке: отдельный «перец» для HMAC токена (опционально; иначе используется SECRET_KEY).
REGISTRATION_TOKEN_PEPPER = os.environ.get("REGISTRATION_TOKEN_PEPPER", "").strip() or None
# Ключ Fernet для pending password (значение от Fernet.generate_key()); иначе ключ выводится из SECRET_KEY.
REGISTRATION_PENDING_PASSWORD_FERNET_KEY = os.environ.get(
    "REGISTRATION_PENDING_PASSWORD_FERNET_KEY", ""
).strip() or None

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

AUTH_USER_MODEL = 'assistant.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'assistant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hakaton.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hakaton.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/cabinet/"
LOGOUT_REDIRECT_URL = "/"

# Почта: DJANGO_EMAIL_* или те же имена, что в fbe-cloud (SMTP_HOST, SMTP_USER, …)
_smtp_host = (os.environ.get("DJANGO_EMAIL_HOST") or os.environ.get("SMTP_HOST", "")).strip()
_smtp_user = (os.environ.get("DJANGO_EMAIL_HOST_USER") or os.environ.get("SMTP_USER", "")).strip()
_smtp_password = (os.environ.get("DJANGO_EMAIL_HOST_PASSWORD") or os.environ.get("SMTP_PASSWORD", "")).strip()
_smtp_port_raw = os.environ.get("DJANGO_EMAIL_PORT") or os.environ.get("SMTP_PORT", "587")
_smtp_from = (
    os.environ.get("DJANGO_DEFAULT_FROM_EMAIL")
    or os.environ.get("SMTP_FROM", "")
    or _smtp_user
    or "Sirius Afisha <noreply@localhost>"
)

EMAIL_HOST = _smtp_host
EMAIL_PORT = int(_smtp_port_raw)
EMAIL_HOST_USER = _smtp_user
EMAIL_HOST_PASSWORD = _smtp_password
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
EMAIL_USE_SSL = os.environ.get("DJANGO_EMAIL_USE_SSL", "").lower() in ("1", "true", "yes")
EMAIL_TIMEOUT = int(os.environ.get("DJANGO_EMAIL_TIMEOUT", "30"))

if EMAIL_HOST and EMAIL_HOST_USER:
    EMAIL_BACKEND = os.environ.get(
        "DJANGO_EMAIL_BACKEND",
        "django.core.mail.backends.smtp.EmailBackend",
    )
    DEFAULT_FROM_EMAIL = _smtp_from
else:
    EMAIL_BACKEND = os.environ.get(
        "DJANGO_EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend",
    )
    DEFAULT_FROM_EMAIL = (
        os.environ.get("DJANGO_DEFAULT_FROM_EMAIL")
        or _smtp_from
    )
