# Generated by Django 6.0.5 on 2026-05-15 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, help_text='Строковый id из UI (случайный hex).', max_length=32)),
                ('title', models.CharField(default='Новый чат', max_length=200)),
                ('sort_rank', models.PositiveIntegerField(default=0)),
                ('focus_event_id', models.IntegerField(blank=True, null=True)),
                ('event_title_hint', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_rank', 'updated_at'),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('time_label', models.CharField(blank=True, default='', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_rows', to='assistant.chatthread')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(fields=('user', 'thread_id'), name='assistant_chatthread_user_thread_uid'),
        ),
    ]
